//
//  ChatServerChatHandler.cs
//
//  Author:
//       Dennis Lapchenko <>
//
//  Copyright (c) 2016 Dennis Lapchenko
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using MMO.Photon.Server;
using MMO.Framework;
using ComplexServerCommon;
using MMO.Photon.Application;
using System.Xml.Serialization;
using ComplexServerCommon.MessageObjects;
using System.IO;
using System.Collections.Generic;
using Photon.SocketServer;
using SubServerCommon.Data.ClientData;


namespace ChatServer.Handlers
{
	public class ChatServerChatHandler : PhotonServerHandler
	{
		public ChatServerChatHandler(PhotonApplication application) : base (application)
		{
		}

		#region implemented abstract members of PhotonServerHandler

		protected override bool OnHandleMessage(IMessage message, PhotonServerPeer serverPeer)
		{
			if(message.Parameters.ContainsKey((byte)ClientParameterCode.Object))
			{
				Guid peerId = new Guid((Byte[])message.Parameters[(byte)ClientParameterCode.PeerId]);
				var chatItem = Xml.Deserialize<ChatItem>(message.Parameters[(byte)ClientParameterCode.Object]);

				switch(chatItem.Type)
				{
					case(ChatType.General):
						chatItem.ByPlayer = Server.ConnectionCollection<SubServerConnectionCollection>().Clients[peerId].ClientData<ChatPlayer>().CharacterName;
						//chatItem.Text - contains client's input string;
						foreach (var client in Server.ConnectionCollection<SubServerConnectionCollection>().Clients)
						{
							var para = new Dictionary<byte, object>()
										{
											{(byte)ClientParameterCode.PeerId, client.Key.ToByteArray()},
											{(byte)ClientParameterCode.Object, Xml.Serialize(chatItem)}
										};
							EventData eventData = new EventData{Code = (byte)ClientEventCode.Chat, Parameters = para};
							client.Value.ClientData<ServerData>().ServerPeer.SendEvent(eventData, new SendParameters());
						}
						break;
					default:
						break;
				}
			}
			return true;
		}

		public override MessageType Type
		{
			get
			{
				return MessageType.Request;
			}
		}

		public override byte Code
		{
			get
			{
				return (byte) ClientOperationCode.Chat;
			}
		}

		public override int? SubCode
		{
			get
			{
				return (int)MessageSubCode.Chat;
			}
		}

		#endregion
	}
}

