// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using MMO.Photon.Server;
using MMO.Photon.Application;
using MMO.Framework;
using ComplexServerCommon;
using RegionServer.Model;


namespace RegionServer.Handlers
{
	public class PlayerInGameHandler : PhotonServerHandler
	{
		public PlayerInGameHandler(PhotonApplication application) : base(application)
		{		}


		#region implemented abstract members of PhotonServerHandler
		public override MessageType Type
		{
			get
			{
				return MessageType.Request;
			}
		}
		public override byte Code
		{
			get
			{
				return (byte)ClientOperationCode.Region;
			}
		}
		public override int? SubCode
		{
			get
			{
				return (int)MessageSubCode.PlayerInGame;
			}
		}
		protected override bool OnHandleMessage(IMessage message, PhotonServerPeer serverPeer)
		{
			Guid peerId = new Guid((Byte[])message.Parameters[(byte)ClientParameterCode.PeerId]);
			var clients = Server.ConnectionCollection<SubServerConnectionCollection>().Clients;
			var instance = clients[peerId].ClientData<CPlayerInstance>();
			instance.Spawn();
			instance.BroadcastUserInfo();
			Log.DebugFormat("Character {0} joined Region Server.", instance.Name);
			//Notify guild members that someone logged in

			//Notify friend list that someone logged in
			return true;
		}

		#endregion
	}
}

