//
//  HandleLoginResponse.cs
//
//  Author:
//       Dennis Lapchenko <>
//
//  Copyright (c) 2016 Dennis Lapchenko
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using MMO.Photon.Server;
using MMO.Photon.Application;
using MMO.Framework;
using ComplexServerCommon;
using MMO.Photon.Client;
using Photon.SocketServer;
using SubServerCommon.Data.ClientData;


namespace ComplexServer.Handlers
{
	public class LoginResponseHandler : PhotonServerHandler
	{
		public LoginResponseHandler(PhotonApplication application) : base(application)
		{
		}

		#region implemented abstract members of PhotonServerHandler

		public override MMO.Framework.MessageType Type {
			get {
				return MessageType.Response;
			}
		}

		public override byte Code {
			get {
				return (byte)ClientOperationCode.Login;
			}
		}

		public override int? SubCode {
			get {
				return (int) MessageSubCode.Login;
			}
		}
		protected override bool OnHandleMessage (IMessage message, PhotonServerPeer serverPeer)
		{
			if(message.Parameters.ContainsKey((byte)ClientParameterCode.PeerId))
			{
				PhotonClientPeer peer;
				Server.ConnectionCollection<PhotonConnectionCollection>().Clients.TryGetValue(
					new Guid((byte[])message.Parameters[(byte)ClientParameterCode.PeerId]), out peer);
				if (peer != null)
				{
					if(message.Parameters.ContainsKey((byte)ClientParameterCode.UserId))
					{
						Log.DebugFormat("Found User {0}", Convert.ToInt32(message.Parameters[(byte)ClientParameterCode.UserId]));
						peer.ClientData<CharacterData>().UserId = Convert.ToInt32(message.Parameters[(byte)ClientParameterCode.UserId]);
					}
					message.Parameters.Remove((byte)ClientParameterCode.PeerId);
					message.Parameters.Remove((byte)ClientParameterCode.UserId);
					message.Parameters.Remove((byte)ClientParameterCode.CharacterId);

					var response = message as PhotonResponse;
					if(response != null)
					{
						peer.SendOperationResponse(new OperationResponse(response.Code, response.Parameters) 
						    { 
								DebugMessage = response.DebugMessage,
								ReturnCode = response.ReturnCode
							}, 	new SendParameters());
					}
					else
					{
						peer.SendOperationResponse(new OperationResponse(message.Code, message.Parameters), new SendParameters());
					}
				}
			}
			return true;
		}

		#endregion
	}
}

