//
//  SelectCharacterResponseHandler.cs
//
//  Author:
//       Dennis Lapchenko <>
//
//  Copyright (c) 2016 Dennis Lapchenko
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using MMO.Photon.Server;
using MMO.Framework;
using MMO.Photon.Application;
using ComplexServerCommon;
using MMO.Photon.Client;
using System.Collections.Generic;
using SubServerCommon;
using Photon.SocketServer;
using SubServerCommon.Data.ClientData;


namespace ComplexServer.Handlers
{
	public class SelectCharacterResponseHandler : PhotonServerHandler
	{
		public SelectCharacterResponseHandler(PhotonApplication application) : base(application)
		{
		}


		public override MessageType Type
		{
			get
			{
				return MessageType.Response;
			}
		}

		public override byte Code
		{
			get
			{
				return (byte)ClientOperationCode.Login;
			}
		}

		public override int? SubCode
		{
			get
			{
				return (int) MessageSubCode.SelectCharacter;
			}
		}

		protected override bool OnHandleMessage(IMessage message, PhotonServerPeer serverPeer)
		{
			if (message.Parameters.ContainsKey((byte)ClientParameterCode.PeerId))
			{
				PhotonClientPeer peer;
				Server.ConnectionCollection<ComplexConnectionCollection>().Clients.TryGetValue(
					new Guid((Byte[])message.Parameters[(byte)ClientParameterCode.PeerId]), out peer);
				if (peer != null)
				{
					int characterId = Convert.ToInt32(message.Parameters[(byte)ClientParameterCode.CharacterId]);
					peer.ClientData<CharacterData>().CharacterId = characterId;

					var para = new Dictionary<byte, object> 
								{
									{(byte)ClientParameterCode.CharacterId, characterId},
									{(byte)ClientParameterCode.PeerId, new Guid((Byte[])message.Parameters[(byte)ClientParameterCode.PeerId]).ToByteArray()},
									{(byte)ClientParameterCode.UserId, peer.ClientData<CharacterData>().UserId}
								};
					//Register client with CHAT Server
					var chatServer = Server.ConnectionCollection<ComplexConnectionCollection>().OnGetServerByType((int)ServerType.Chat);
					if (chatServer != null)
					{
						chatServer.SendEvent(new EventData((byte)ServerEventCode.CharacterRegister){Parameters = para}, new SendParameters());
					}

					//Register client with REGION Server
					var regionServer = Server.ConnectionCollection<ComplexConnectionCollection>().OnGetServerByType((int)ServerType.Region);
					if (chatServer != null)
					{
						peer.CurrentServer = regionServer;
						regionServer.SendEvent(new EventData((byte)ServerEventCode.CharacterRegister){Parameters = para}, new SendParameters());
					}

					message.Parameters.Remove((byte)ClientParameterCode.PeerId);
					message.Parameters.Remove((byte)ClientParameterCode.UserId);
					message.Parameters.Remove((byte)ClientParameterCode.CharacterId);

					var response = message as PhotonResponse;
					if (response != null)
					{
						peer.SendOperationResponse(new OperationResponse(response.Code, response.Parameters) 
						                                 { ReturnCode = response.ReturnCode, DebugMessage = response.DebugMessage}, new SendParameters());
					}
					else
					{
						peer.SendOperationResponse(new OperationResponse(message.Code, message.Parameters), new SendParameters());
					}
					
				}
			}
			return true;
		}
	}
}

