//
//  TeleportToLocation.cs
//
//  Author:
//       Dennis Lapchenko <>
//
//  Copyright (c) 2016 Dennis Lapchenko
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using RegionServer.Model;
using ComplexServerCommon;


namespace RegionServer.Model.ServerEvents
{
	public class TeleportToLocation : ServerPacket
	{
		public TeleportToLocation(CObject obj, float x, float y, float z, short heading) : this(obj, new Position(x,y,z, heading))
		{
		}

		public TeleportToLocation(CObject obj, Position pos) : base(ClientEventCode.ServerPacket, MessageSubCode.TeleportToLocation)
		{
			AddParameter(obj.ObjectId, ClientParameterCode.ObjectId);
			AddSerializedParameter(pos, ClientParameterCode.Object);
		}
	}
}

