// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using RegionServer.Model.Interfaces;


namespace RegionServer.Model.Stats
{
	public class Level : IStat
	{
		public Level()
		{
		}

		#region IStat implementation

		public string Name {get { return "Level"; } }
		public bool IsBaseStat { get { return true; } }
		public bool IsNonZero { get { return true; } }
		public float BaseValue { get; set; }

		#endregion
	}
}

