// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using RegionServer.Model.Interfaces;
using RegionServer.Model;


namespace RegionServer.Calculators.Functions
{
	public class FunctionMultiply : IFunction
	{
		private readonly ILambda _lambda;
		
		#region IFunction implementation
		public IStat Stat {get;}
		public int Order {get;}
		public CObject Owner {get; set;}
		public ICondition Condition {get; set;}
		
		public void Calc(Environment env)
		{
			if(Condition == null || Condition.Test(env))
			{
				env.Value *= _lambda.Calculate(env);
			}
		}
		#endregion
		
		public FunctionMultiply(IStat stat, int order, CObject owner, ILambda lambda)
		{
			Stat = stat;
			Order = order;
			Owner = owner;
			_lambda = lambda;
		}
		
	}
}

