//
//  PositionData.cs
//
//  Author:
//       Dennis Lapchenko <>
//
//  Copyright (c) 2016 Dennis Lapchenko
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace ComplexServerCommon.MessageObjects
{
	[Serializable]
	public class PositionData
	{
		public float X {get; set;}
		public float Y {get; set;}
		public float Z {get; set;}
		
		public short Heading {get;set;} //0 - 65535 0.00549deg per value (to save message size)

		public PositionData()
			: this (0,0,0,0)
		{}

		public PositionData(float x, float y, float z)
			:this (x,y,z,0)
		{}

		public PositionData(float x, float y, float z, short heading)
		{
			X = x;
			Y = y;
			Z = z;
			Heading = heading;
		}
	}
}

